force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Equipment_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Category__c</fullName>
    <label>Equipment Category</label>
    <referenceTo>Equipment_Category__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Category__c/Equipment_Category__c.object-meta.xml
<CustomObject>
    <label>Equipment Category</label>
    <nameField>
        <label>Equipment Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/Equipment_Set__c.object-meta.xml
<CustomObject>
    <label>Equipment Set</label>
    <nameField>
        <displayFormat>EqSet-{0000}</displayFormat>
        <label>Equipment to Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <description>Equipment for Proposal</description>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals List</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Equipment List</relationshipLabel>
    <relationshipName>Proposal</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/ProposalCreationPageControllerTest.cls
@IsTest
public with sharing class ProposalCreationPageControllerTest {

	@IsTest
	public static void getCategoriesServerTest() {

		Equipment_Category__c equipmentCategory = TestDataFactory.createSingleEquipmentCategory();

		Test.startTest();
		List<Equipment_Category__c> equipmentCategoriesFromTestedMethod = ProposalCreationPageController.getCategoriesServer();
		Test.stopTest();

		System.assertEquals(1, equipmentCategoriesFromTestedMethod.size());
		System.assertEquals(equipmentCategory.Id, equipmentCategoriesFromTestedMethod[0].Id);
	}

	@IsTest
	public static void getProductsServerTest() {
		List<Equipment__c> equipments = TestDataFactory.createEquipmentsWithEquipmentCategoryList(5);

		Map<String, String> params = new Map<String, String>{
				'nameKey' => 'equip',
				'categoryId' => equipments[0].Equipment_Category__c
		};

		Test.startTest();
		List<Equipment__c> equipmentsFromTestedMethod = ProposalCreationPageController.getProductsServer(params);
		Test.stopTest();

		System.assertEquals(equipments.size(), equipmentsFromTestedMethod.size());
	}

	@IsTest
	public static void setNewProposalWithProductsServerTest() {

		Opportunity opportunity = TestDataFactory.createOpportunitiesWithAccounts(1, false)[0];
		Equipment__c equipment = TestDataFactory.createEquipmentsWithEquipmentCategoryList(1)[0];


		Map<String, List<Map<String, String>>> params = new Map<String, List<Map<String, String>>>{
				'proposalData' => new List<Map<String, String>>{
						new Map<String, String>{
								'Opportunity__c' => opportunity.Id,
								'Name' => 'TestProposalName777',
								'Status__c' => 'Draft'
						}
				},
				'productsData' => new List<Map<String, String>>{
						new Map<String, String>{
								'Equipment__c' => equipment.Id,
								'Quantity__c' => '10'
						}
				}
		};

		Test.startTest();
		ProposalCreationPageController.setNewProposalWithProductsServer(params);
		Test.stopTest();

		List<Proposal__c> proposalTested = [SELECT Name, Opportunity__c FROM Proposal__c WHERE Opportunity__c = :opportunity.Id];
		List<Equipment_Set__c> equipmentSetTested = [SELECT Equipment__c, Proposal__c, Quantity__c FROM Equipment_Set__c WHERE Proposal__r.Opportunity__c = :opportunity.Id];

		System.assertEquals(false, proposalTested.isEmpty());
		System.assertEquals(false, equipmentSetTested.isEmpty());
		System.assertEquals('TestProposalName777', proposalTested[0].Name);
		System.assertEquals(10, equipmentSetTested[0].Quantity__c);
	}
}