force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Equipment_Category__c.field-meta.xml
<CustomField>
    <fullName>Equipment_Category__c</fullName>
    <label>Equipment Category</label>
    <referenceTo>Equipment_Category__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Vendor does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment_Category__c/Equipment_Category__c.object-meta.xml
<CustomObject>
    <label>Equipment Category</label>
    <nameField>
        <label>Equipment Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/Equipment_Set__c.object-meta.xml
<CustomObject>
    <label>Equipment Set</label>
    <nameField>
        <displayFormat>EqSet-{0000}</displayFormat>
        <label>Equipment to Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <description>Equipment for Proposal</description>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals List</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Equipment List</relationshipLabel>
    <relationshipName>Proposal</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProposalCreationPageController.cls
/**
 * @author Olexander Piharev
 * @version 1.0
 *
 * @since 2023-01-17
 */
public with sharing class ProposalCreationPageController {

	/**
	 * The method gets all Equipment Category records.
	 *
	 * @return a list of Equipment Category
	 */
	@AuraEnabled
	public static List<Equipment_Category__c> getCategoriesServer() {

		return [
				SELECT Id, Name
				FROM Equipment_Category__c
				ORDER BY Name
		];
	}

	/**
	 * The method gets Equipment records that Name match to entered text and Equipment Category.
	 *
	 * @param params : nameKey - a part of Equipment Name; categoryId - Equipment Category Id
	 *
	 * @return a list of found by filter Equipment
	 */
	@AuraEnabled
	public static List<Equipment__c> getProductsServer(Map<String, String> params) {
		System.debug('Product params: ' + params);

		String categoryId = params.get('categoryId');
		String nameKey = params.get('nameKey');

		categoryId = categoryId == null ? '' : categoryId;
		nameKey = nameKey == null ? '' : nameKey;

		String s = 'SELECT Id, Name, Cost__c, Equipment_Category__r.Name, Vendor__r.Name ';
		String f = ' FROM Equipment__c ';
		String w = ' WHERE Equipment_Category__c = \'' + categoryId + '\' AND Name LIKE \'%' + nameKey + '%\' ' ;
		String o = ' ORDER BY Name';
		String l = ' LIMIT 2000';

		return Database.query(s + f + w + o + l);
	}

	/**
	 * The method insert new Proposal and fetch method that creates related EquipmentSets
	 *
	 * @param params : proposalData - data for proposal creation;
	 * productsDataList - list of related to newly Proposal Equipments
	 */
	@AuraEnabled
	public static void setNewProposalWithProductsServer(Map<String, List<Map<String, String>>> params) {
		System.debug('Proposal creation params: ' + params);
		// Proposal__c newProposal = (Proposal__c) params.get('proposalData')[0]; // TODO figure out why casting not working

		Map<String, String> proposalData = params.get('proposalData')[0];
		List<Map<String, String>> productsDataList = params.get('productsData');

		System.debug('Proposal: ' + proposalData);
		System.debug('Products: ' + productsDataList);

		Proposal__c newProposal = new Proposal__c(Name = proposalData.get('Name'), Opportunity__c = proposalData.get('Opportunity__c'), Status__c = proposalData.get('Status__c'));

		insert newProposal;

		saveNewEquipmentSets(newProposal.Id, productsDataList);
	}

	/**
	 * The method creates EquipmentsSets to specified Proposal
	 *
	 * @param proposalId - Proposal id
	 * @param productsDataList - list of Equipments data
	 */
	private static void saveNewEquipmentSets(String proposalId, List<Map<String, String>> productsDataList) {
		List<Equipment_Set__c> eqList = new List<Equipment_Set__c>();
		for (Map<String, String> e : productsDataList) {
			eqList.add(new Equipment_Set__c(Proposal__c = proposalId, Equipment__c = e.get('Equipment__c'), Quantity__c = Decimal.valueOf(e.get('Quantity__c'))));
		}

		insert eqList;
	}
}