force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/Equipment_Set__c.object-meta.xml
<CustomObject>
    <label>Equipment Set</label>
    <nameField>
        <displayFormat>EqSet-{0000}</displayFormat>
        <label>Equipment to Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <description>Equipment for Proposal</description>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals List</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Equipment List</relationshipLabel>
    <relationshipName>Proposal</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/tests/ProposalTriggerTest.cls
@IsTest
public with sharing class ProposalTriggerTest {

	private static final List<Proposal__c> PROPOSALS = TestDataFactory.createProposalsWithAccountsAndOpportunities(1);

	@IsTest
	public static void checkOnExistedEqSetInProposalTest() {
		Equipment__c equipment = TestDataFactory.createEquipmentsWithEquipmentCategoryList(1)[0];
		Equipment_Set__c equipmentSet1 = new Equipment_Set__c(Equipment__c = equipment.Id, Proposal__c = PROPOSALS[0].Id);
		insert equipmentSet1;

		Equipment_Set__c equipmentSet2 = new Equipment_Set__c(Equipment__c = equipment.Id, Proposal__c = PROPOSALS[0].Id);

		Test.startTest();
		Database.SaveResult result = Database.insert(equipmentSet2, false);
		Test.stopTest();

		System.debug(result);

		System.assert(!result.isSuccess());
		System.assert(result.getErrors().size() > 0);
		System.assertEquals('Such Equipment already exists in this Proposal.', result.getErrors()[0].getMessage());
	}

	@IsTest
	public static void deletionProposalTest() {
		Proposal__c proposal = PROPOSALS[0];
		proposal.Status__c = 'Sent';
		update proposal;

		Test.startTest();
		Database.DeleteResult result = Database.delete(proposal, false);
		Test.stopTest();

		System.assert(!result.isSuccess());
		System.assert(result.getErrors().size() > 0);
		System.assertEquals('Only proposals with the status "Draft" can be deleted.',
				result.getErrors()[0].getMessage());
	}

}