force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/Equipment_Set__c.object-meta.xml
<CustomObject>
    <label>Equipment Set</label>
    <nameField>
        <displayFormat>EqSet-{0000}</displayFormat>
        <label>Equipment to Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <description>Equipment for Proposal</description>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals List</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Equipment List</relationshipLabel>
    <relationshipName>Proposal</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/tests/ProposalPDFControllerTest.cls
@IsTest
public with sharing class ProposalPDFControllerTest {

	@TestSetup
	private static void testSetup() {
		Proposal__c proposal = TestDataFactory.createProposalsWithAccountsAndOpportunities(1)[0];

		Equipment__c equipment = TestDataFactory.createEquipmentsWithEquipmentCategoryList(1)[0];
		Equipment_Set__c equipmentSet = new Equipment_Set__c(Proposal__c = proposal.Id, Equipment__c = equipment.Id, Quantity__c = 13);
		insert equipmentSet;
	}

	@IsTest
	public static void testProposalPDFPage() {
		Id proposalId = [SELECT Id, Name FROM Proposal__c WHERE Name = 'TestProposal0'].Id;

		Test.startTest();
		PageReference pageRef = Page.ProposalRenderPDF;
		pageRef.getParameters().put('Id', proposalId);
		Test.setCurrentPage(pageRef);

		ProposalPDFController testProp = new ProposalPDFController();
		Proposal__c prop = ProposalPDFController.proposal;
		List <Equipment_Set__c> equipmentItems = ProposalPDFController.equipmentItems;
		OpportunityContactRole primaryContact = ProposalPDFController.primaryContact;
		Test.stopTest();

		System.assertEquals('TestProposal0', prop.Name);
		System.assertEquals(13, equipmentItems[0].Quantity__c);
		System.assert(primaryContact != null);
	}

}