force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>14</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/Equipment_Set__c.object-meta.xml
<CustomObject>
    <label>Equipment Set</label>
    <nameField>
        <displayFormat>EqSet-{0000}</displayFormat>
        <label>Equipment to Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <description>Equipment for Proposal</description>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals List</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Equipment List</relationshipLabel>
    <relationshipName>Proposal</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Total_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Price__c</fullName>
    <formula>Total_Cost__c/(1- Margin__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Total_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Total_Quantity__c</fullName>
    <description>The total quantity of all equipment.</description>
    <label>Total Quantity</label>
    <summarizedField>Equipment_Set__c.Quantity__c</summarizedField>
    <summaryForeignKey>Equipment_Set__c.Proposal__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/ProposalPDFController.cls
/**
 * @author Olexander Piharev
 * @version 1.0
 *
 * @since 2023-01-27
 */
public class ProposalPDFController {

	private static final String propId = ApexPages.currentPage().getParameters().get('Id');

	public ProposalPDFController() {
		System.debug('Proposal Id from VF Controller: ' + propId);
	}

	public static Proposal__c proposal {
		get {
			if (proposal == null) {
				proposal = [
						SELECT Name, Opportunity__c, Opportunity__r.Account.Name, Total_Quantity__c, Total_Price__c
						FROM Proposal__c
						WHERE Id = :propId
						LIMIT 1
				];
			}
			return proposal;
		}
		set;
	}

	public static List <Equipment_Set__c> equipmentItems {
		get {
			if (equipmentItems == null) {
				equipmentItems = [
						SELECT Name, Equipment__r.Name, Cost__c, Quantity__c, Price__c, Price_per_1__c
						FROM Equipment_Set__c
						WHERE Proposal__c = :propId
						ORDER BY Name
				];
			}
			return equipmentItems;
		}
		set;
	}

	public static OpportunityContactRole primaryContact {
		get {
			if (primaryContact == null) {
				primaryContact = [
						SELECT Contact.Name, Contact.MailingCountry, Contact.MailingCity, Contact.MailingState, Contact.MailingStreet, Contact.MailingPostalCode,
								Contact.Email
						FROM OpportunityContactRole
						WHERE OpportunityId = :proposal.Opportunity__c
						// AND IsPrimary = TRUE
						LIMIT 1
				];
			}
			return primaryContact;
		}
		set;
	}

}