force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <label>Equipment</label>
    <nameField>
        <label>Equipment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/Equipment_Set__c.object-meta.xml
<CustomObject>
    <label>Equipment Set</label>
    <nameField>
        <displayFormat>EqSet-{0000}</displayFormat>
        <label>Equipment to Proposal Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Sets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment_Set__c/fields/Equipment__c.field-meta.xml
<CustomField>
    <fullName>Equipment__c</fullName>
    <description>Equipment for Proposal</description>
    <label>Equipment</label>
    <referenceTo>Equipment__c</referenceTo>
    <relationshipLabel>Proposals List</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Equipment_Set__c/fields/Proposal__c.field-meta.xml
<CustomField>
    <fullName>Proposal__c</fullName>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Equipment List</relationshipLabel>
    <relationshipName>Proposal</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ProposalTriggerHelper.cls
/**
 * @author Olexander Piharev
 * @version 1.0
 *
 * @since 2023-01-16
 */
public without sharing class ProposalTriggerHelper {

	/**
	 * This method check on duplicates Equipment in one Proposal
	 *
	 * @param propId - current Proposal Id
	 *
	 * @return message error message if plurality found
	 */
	public static String checkOnExistedEqSetInProposal(Id propId) {
		String message = '';
		Set <Id> eqIdsSet = new Set<Id>();
		List <Equipment_Set__c> eqListInProposal = [SELECT Id, Equipment__c FROM Equipment_Set__c WHERE Proposal__c = :propId];
		if (!eqListInProposal.isEmpty()) {
			for (Equipment_Set__c eSet : eqListInProposal) {
				eqIdsSet.add(eSet.Equipment__c);
			}
			if (eqListInProposal.size() != eqIdsSet.size()) message = 'Such Equipment already exists in this Proposal.';
		}
		return message;
	}
}