force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Proposal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>draft</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>accepted</fullName>
            </value>
            <value>
                <fullName>rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProposalsController.cls
/**
 * @author Olexander Piharev
 * @version 1.0
 *
 * @since 2023-01-17
 */
public with sharing class ProposalsController {

	/**
	 * This method get all proposal of related Opportunity
	 *
	 * @param oppId - related Opportunity Id
	 *
	 * @return proposals list
	 */
	@AuraEnabled
	public static List<Proposal__c> getProposalsServer(Id oppId) {
		System.debug('Opp Id: ' + oppId);
		return [
				SELECT Id, Name, Opportunity__r.Name, Status__c, Total_Price__c, isActionsDisabled__c
				FROM Proposal__c
				WHERE Opportunity__r.Id = :oppId
				ORDER BY CreatedDate
		];
	}

	/**
	 * The method for deleting single proposal by id
	 *
	 * @param propId -proposal Id
	 */
	@AuraEnabled
	public static void deleteSinglePropServer(Id propId) {
		System.debug('Proposal Id to delete: ' + propId);
		delete [SELECT Id FROM Proposal__c WHERE Id = :propId];
	}

}