force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Proposals</relationshipLabel>
    <relationshipName>Proposals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/tests/ProposalsControllerTest.cls
@IsTest
public with sharing class ProposalsControllerTest {

	private static final List<Proposal__c> PROPOSALS = TestDataFactory.createProposalsWithAccountsAndOpportunities(1);

	@IsTest
	public static void getProposalsServerTest() {
		Test.startTest();
		List<Proposal__c> proposalsFromTestedMethod = ProposalsController.getProposalsServer(PROPOSALS[0].Opportunity__c);
		Test.stopTest();
		System.assertEquals(PROPOSALS.size(), proposalsFromTestedMethod.size());
		System.assertEquals(PROPOSALS[0].Id, proposalsFromTestedMethod[0].Id);
	}

	@IsTest
	public static void deleteSinglePropServerTest() {
		Id pId = PROPOSALS[0].Id;
		Test.startTest();
		ProposalsController.deleteSinglePropServer(pId);
		Test.stopTest();
		System.assertEquals(0, [SELECT COUNT() FROM Proposal__c WHERE Id = :pId]);
	}

}